version: '3.8'
services:
  gol-react:
    build:
      context: ./frontend
      target: production
      args:
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - webnet
  gol-fastapi:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - webnet
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"                         # ENABLE FOR SSL
    volumes:
      #- ./nginx-nossl:/etc/nginx/conf.d  # DISABLE FOR SSL
      - ./nginx-ssl:/etc/nginx/conf.d     # ENABLE FOR SSL
      - ./ssl/certs:/etc/ssl/certs        # ENABLE FOR SSL
      - ./ssl/private:/etc/ssl/private    # ENABLE FOR SSL
    networks:
      - webnet
networks:
  webnet: