version: '3.8'
services:
  react:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
  fastapi:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload