version: '3.8'
services:
  gol-react:
    build:
      context: ./frontend
      target: production
      args:
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - webnet
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - webnet
networks:
  webnet: