version: '3.8'
services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    # Additional production-specific configurations like logging, etc.

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # In production, you might want to bind to port 80 or 443 (if SSL is configured)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    # Additional Nginx production configurations like SSL, rate limiting, etc.
